# Generated by Django 5.1.1 on 2024-10-10 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_startquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startquestion',
            options={'verbose_name': 'Вопросы о начале работы'},
        ),
        migrations.CreateModel(
            name='EndQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'Вопросы о конце работы',
            },
        ),
        migrations.CreateModel(
            name='ReportQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'Отчёты о работе',
            },
        ),
    ]
