# Generated by Django 5.1.1 on 2024-10-10 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_startquestion_options_endquestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportquestion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='startquestion',
            name='user',
        ),
        migrations.DeleteModel(
            name='EndQuestion',
        ),
        migrations.DeleteModel(
            name='ReportQuestion',
        ),
        migrations.DeleteModel(
            name='StartQuestion',
        ),
        migrations.DeleteModel(
            name='TelegramUser',
        ),
    ]
