# Generated by Django 5.1.1 on 2024-10-10 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_media_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='news.news'),
        ),
    ]
