# Generated by Django 5.1.1 on 2024-10-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_rename_reportquestion_report_alter_report_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'verbose_name': 'Напоминание', 'verbose_name_plural': 'Напоминания'},
        ),
        migrations.AlterModelOptions(
            name='vacation',
            options={'verbose_name': 'Отпуск', 'verbose_name_plural': 'Отпуска'},
        ),
    ]
