# Generated by Django 5.1.1 on 2024-10-12 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_alter_reminder_options_alter_vacation_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='role',
        ),
        migrations.AlterField(
            model_name='endquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_questions', to='telegram.telegramuser'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='telegram.telegramuser'),
        ),
        migrations.AlterField(
            model_name='startquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_questions', to='telegram.telegramuser'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='type',
            field=models.CharField(choices=[('start_question', 'Вопрос о начале дня'), ('report', 'Отчёт'), ('end_question', 'Вопрос о конце дня'), ('other', 'Другое')], max_length=16, verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation', to='telegram.telegramuser'),
        ),
    ]
