# Generated by Django 5.1.1 on 2024-10-04 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'verbose_name': 'Чек-лист', 'verbose_name_plural': 'Чек-листы'},
        ),
        migrations.AlterField(
            model_name='checklist',
            name='file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['xlsx'])], verbose_name='Файл .xlsx'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='type',
            field=models.CharField(choices=[('check_list', 'Чек-лист'), ('estimate', 'Смета')], default='check_list', max_length=10, verbose_name='Тип чек-листа'),
        ),
    ]
